services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0.20
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "mosquitto_pub -h localhost -p 1883 -t 'health/check' -m 'healthcheck'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  zigbee2mqtt_windows:
    image: koenkk/zigbee2mqtt:2.1.1

    container_name: zigbee2mqtt_windows
    restart: unless-stopped
    volumes:
      - ./mqtt/config/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Budapest
    # For windows, to use the com port. For more details, see zigbee2mqtt/README.md
    privileged: true
    depends_on:
      mqtt_broker:
        condition: service_healthy
